---
  - name: "show environment"
    shell: env
  - name: "synchronize backend installations"
    become: yes
    synchronize:
      src: ../../backend/node_modules
      dest: /home/ubuntu/app
      recursive: true
  - name: "synchronize backend binaries"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/app
      recursive: true
  - name: "delete anything that is running"
    become: true
    command: pm2 delete all
    ignore_errors: true
  - name: "start server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/app/dist